<definitions targetNamespace="http://katastr.cuzk.cz/ctios/v2.8"
	xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://katastr.cuzk.cz/ctios/v2.8"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:utype="http://katastr.cuzk.cz/ctios/types/v2.8"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
	xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
	<!-- Verze WSDL: 2.8.0 -->
	<wsp:Policy name="UsernameToken" wsu:Id="IsknWSSecurityPolicy">
		<sp:SupportingTokens>
			<wsp:Policy>
				<sp:UsernameToken sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
					<wsp:Policy>
						<sp:WssUsernameToken11 />
					</wsp:Policy>
				</sp:UsernameToken>
			</wsp:Policy>
		</sp:SupportingTokens>
	</wsp:Policy>
	<types>
		<xsd:schema targetNamespace="http://katastr.cuzk.cz/ctios/types/v2.8" elementFormDefault="qualified">
			<xsd:include schemaLocation="ctios_v28.xsd" />
		</xsd:schema>
	</types>
	<message name="ctiOsRequest">
		<part name="input" element="utype:CtiOsRequest" />
	</message>
	<message name="ctiOsResponse">
		<part name="output" element="utype:CtiOsResponse" />
	</message>

	<portType name="ctios">
		<operation name="ctios">
			<input message="tns:ctiOsRequest" />
			<output message="tns:ctiOsResponse" />
		</operation>
	</portType>

	<binding name="ctiosSOAPBinding" type="tns:ctios">
		<wsp:PolicyReference URI="#IsknWSSecurityPolicy" />
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<operation name="ctios">
			<soap:operation style="document" soapAction="http://katastr.cuzk.cz/ctios/ctios" />
			<input>
				<soap:body use="literal" parts="input" />
			</input>
			<output>
				<soap:body use="literal" parts="output" />
			</output>
		</operation>
	</binding>

	<service name="ctios">
		<port name="ctiosSoapHttpPort" binding="tns:ctiosSOAPBinding">
			<soap:address location="https://katastr.cuzk.cz/ws/ctios/2.8/ctios" />
		</port>
	</service>
</definitions>
