/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import wsdpctios.Log;

/**
 *
 * @author barandovskip
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
        jTextFieldEndpoint.setText(Config.loadEndpoint());
        jTextFieldUserName.setText(Config.loadUserName());
        jPasswordField.setText(Config.loadPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInputFile = new javax.swing.JLabel();
        jButtonInputFile = new javax.swing.JButton();
        jTextFieldUserName = new javax.swing.JTextField();
        jLabelUserName = new javax.swing.JLabel();
        jTextFieldInputFile = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jLabelOutputFile = new javax.swing.JLabel();
        jButtonOutputFile = new javax.swing.JButton();
        jTextFieldOutputFile = new javax.swing.JTextField();
        jComboBoxCharSet = new javax.swing.JComboBox<>();
        jButtonStart = new javax.swing.JButton();
        jLabelCharSet = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        jTextFieldEndpoint = new javax.swing.JTextField();
        jLabelEndpoint = new javax.swing.JLabel();
        jCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ctiOS pro VFK");
        setLocation(new java.awt.Point(350, 350));
        setResizable(false);

        jLabelInputFile.setText("Vstupní soubor");

        jButtonInputFile.setText("...");
        jButtonInputFile.setAlignmentX(350.0F);
        jButtonInputFile.setAlignmentY(350.0F);
        jButtonInputFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInputFileActionPerformed(evt);
            }
        });

        jLabelUserName.setText("Uživatelské jméno");

        jLabelPassword.setText("Heslo");

        jLabelOutputFile.setText("Výstupní soubor");

        jButtonOutputFile.setText("...");
        jButtonOutputFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOutputFileActionPerformed(evt);
            }
        });

        jComboBoxCharSet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UTF-8", "WE8ISO8859P2", "EE8MSWIN1250" }));

        jButtonStart.setText("Start");
        jButtonStart.setEnabled(false);
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jLabelCharSet.setText("Kódová stránka výstupního souboru");

        jButtonSave.setText("Uložit");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jLabelEndpoint.setText("Endpoint");

        jCheckBox.setText("<html>Mám právní důvody k získávání osobních údajů oprávněných subjektů a mám zákonný důvod na jejich shromažďování.</html>");
        jCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/vykricnik.png"))); // NOI18N
        jLabel1.setText("<html>Stažení všech osobních údajů volaných oprávněných subjektů je na straně ČÚZK logováno a monitorováno!</html>");
        jLabel1.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEndpoint)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jButtonStart, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                    .addComponent(jComboBoxCharSet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldInputFile)
                            .addComponent(jTextFieldOutputFile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonOutputFile, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonInputFile, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCharSet)
                    .addComponent(jLabelUserName)
                    .addComponent(jLabelOutputFile)
                    .addComponent(jLabelEndpoint)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldUserName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPassword)
                                    .addComponent(jLabelInputFile))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPasswordField))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelEndpoint)
                .addGap(4, 4, 4)
                .addComponent(jTextFieldEndpoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUserName)
                .addGap(1, 1, 1)
                .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPassword)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelInputFile)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInputFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelOutputFile)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOutputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOutputFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCharSet)
                .addGap(1, 1, 1)
                .addComponent(jComboBoxCharSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonStart)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInputFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInputFileActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        jfc.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("soubory *.txt, *.csv", "txt", "csv");
        jfc.addChoosableFileFilter(filter);

        String inputPath = Config.loadInputPath();
        if (inputPath != null) {
            jfc.setCurrentDirectory(new File(inputPath).getParentFile());
        }

        int returnValue = jfc.showOpenDialog(gui.JFrame.this);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            jTextFieldInputFile.setText(jfc.getSelectedFile().getPath());
            Config.saveInputPath(jfc.getSelectedFile().getPath());
        }


    }//GEN-LAST:event_jButtonInputFileActionPerformed

    private void jButtonOutputFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOutputFileActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("soubor *.vfk", "vfk");
        jfc.addChoosableFileFilter(filter);

        String outputPath = Config.loadOutputPath();
        if (outputPath != null) {
            jfc.setCurrentDirectory(new File(outputPath).getParentFile());
        }

        int returnValue = jfc.showSaveDialog(gui.JFrame.this);

        if (returnValue == JFileChooser.APPROVE_OPTION) {

            String filename = jfc.getSelectedFile().toString();
            if (!filename.endsWith(".vfk")) {
                filename += ".vfk";
            }

            File file = new File(filename);
            if (file.exists()) {
                int response = JOptionPane.showConfirmDialog(null, //
                        "Přejete si přepsat existující soubor?", //
                        "Potvrzení", JOptionPane.YES_NO_OPTION, //
                        JOptionPane.QUESTION_MESSAGE);
                if (response != JOptionPane.YES_OPTION) {
                    return;
                }
            }

            //jTextFieldOutputFile.setText(jfc.getSelectedFile().getPath());
            jTextFieldOutputFile.setText(filename);
            Config.saveOutputPath(jfc.getSelectedFile().getPath());

        }


    }//GEN-LAST:event_jButtonOutputFileActionPerformed

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed

        try {
            if (jTextFieldInputFile.getText().equals("") || jTextFieldOutputFile.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Vyplňte všechny kolonky.", "Upozornění", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            wsdpctios.Main.run(jTextFieldInputFile.getText(),
                    jTextFieldOutputFile.getText(),
                    jComboBoxCharSet.getSelectedItem().toString(),
                    jTextFieldEndpoint.getText(),
                    jTextFieldUserName.getText(),
                    new String(jPasswordField.getPassword()));
            JOptionPane.showMessageDialog(null, "Hotovo.\n\n" + Log.getString(), "Upozornění", JOptionPane.INFORMATION_MESSAGE);
            Log.log(Log.getString());
            Log.resetString();
        } catch (Exception ex) {
            System.err.println(ex.getMessage() + " " + ex.getLocalizedMessage());
        }


    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        Config.save(jTextFieldEndpoint.getText(),
                jTextFieldUserName.getText(),
                new String(jPasswordField.getPassword()));

    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxActionPerformed
        if (jCheckBox.isSelected() == true) {
            jButtonStart.setEnabled(true);
        } else {
            jButtonStart.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInputFile;
    private javax.swing.JButton jButtonOutputFile;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JCheckBox jCheckBox;
    private javax.swing.JComboBox<String> jComboBoxCharSet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCharSet;
    private javax.swing.JLabel jLabelEndpoint;
    private javax.swing.JLabel jLabelInputFile;
    private javax.swing.JLabel jLabelOutputFile;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldEndpoint;
    private javax.swing.JTextField jTextFieldInputFile;
    private javax.swing.JTextField jTextFieldOutputFile;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
